language: java

before_install:
    - sudo apt-get update > /dev/null
    
jdk:
  - oraclejdk8
  - oraclejdk7

branches:
  only:
    - master
    - 2.2

after_success:
  - echo "<settings><servers><server><id>ossrh</id><username>\${env.OSSRH_USER}</username><password>\${env.OSSRH_PASS}</password></server></servers></settings>" > ~/settings.xml
  - mvn deploy --settings ~/settings.xml